# Generated by Django 3.1.2 on 2020-10-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='shopping_cart',
        ),
    ]
