# Generated by Django 3.1.2 on 2020-10-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
