# Generated by Django 3.1.2 on 2020-10-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='weight',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sub_category',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='material',
            field=models.CharField(default='synthetic', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock',
            field=models.IntegerField(default=5),
        ),
    ]
