# Generated by Django 3.1.2 on 2020-11-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20201102_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='id',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
