# Generated by Django 3.1.2 on 2020-11-02 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20201102_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
    ]
