# Generated by Django 3.1.2 on 2020-11-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20201102_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_id',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
