# Generated by Django 3.1.2 on 2020-11-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(default='falchion.jpg', max_length=255),
        ),
    ]
