# Generated by Django 3.1.2 on 2020-11-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20201107_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(default='falchion.jpg', max_length=255),
        ),
    ]
