# Generated by Django 3.1.2 on 2020-11-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_remove_article_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(default='', max_length=255),
        ),
    ]
